### ISSUE TITLE
The deletion of Deployment won't delete the ServiceEntry created

### ISSUE THREAD

**Issue by wenxian** [istio-ecosystem/admiral#166]
I have a deployment 
```apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
  namespace: sample-showgtp
  labels:
    identity: greeting-sample-showgtp
    env: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: greeting
        identity: greeting-sample-showgtp
        env: default
```
Then the ` default.greeting-sample-showgtp.global-se` will be created. However, after the deletion of deployment, ` default.greeting-sample-showgtp.global-se` is still there

**Comment by aattuluri** [comment]
@wenxian This has been fixed in the latest (master) but not yet released, what version of admiral are you using?

**Comment by wenxian** [comment]
Running on Admiral 1.1

**Comment by aattuluri** [comment]
Try the `latest` tag of admiral

**Comment by wenxian** [comment]
Here is my experiment: deploy greeting service in both east and west. `default.greeting-sample-showgtp.global-se` has two endpoints in both east and west. After the deletion of greeting in east, i see west has the endpoint deleted, but east is still the same

East:
```
Name:         default.greeting-sample-showgtp.global-se
Namespace:    admiral-sync
Labels:       identity=greeting-sample-showgtp
Annotations:  <none>
API Version:  networking.istio.io/v1beta1
Kind:         ServiceEntry
Metadata:
  Creation Timestamp:  2021-01-25T23:41:37Z
  Generation:          8
  Resource Version:    63962592
  Self Link:           /apis/networking.istio.io/v1beta1/namespaces/admiral-sync/serviceentries/default.greeting-sample-showgtp.global-se
  UID:                 ea88024a-c6a1-471d-a14d-f90af02364f1
Spec:
  Addresses:
    240.0.10.6
  Endpoints:
    Address:   greeting.sample-showgtp.svc.cluster.local
    Locality:  us-east-1
    Ports:
      Http:    80
    Address:   <WEST-NLB>
    Locality:  us-west-2
    Ports:
      Http:  15443
  Hosts:
    default.greeting-sample-showgtp.global
  Location:  MESH_INTERNAL
  Ports:
    Name:      http
    Number:    80
    Protocol:  http
  Resolution:  DNS
Events:        <none>
```
West
```Name:         default.greeting-sample-showgtp.global-se
Namespace:    admiral-sync
Labels:       identity=greeting-sample-showgtp
Annotations:  <none>
API Version:  networking.istio.io/v1beta1
Kind:         ServiceEntry
Metadata:
  Creation Timestamp:  2021-01-23T02:13:08Z
  Generation:          1996
  Resource Version:    61182242
  Self Link:           /apis/networking.istio.io/v1beta1/namespaces/admiral-sync/serviceentries/default.greeting-sample-showgtp.global-se
  UID:                 220c5401-3b2e-422a-a1c8-0152a825c247
Spec:
  Addresses:
    240.0.10.6
  Endpoints:
    Address:   greeting.sample-showgtp.svc.cluster.local
    Locality:  us-west-2
    Ports:
      Http:  80
  Hosts:
    default.greeting-sample-showgtp.global
  Location:  MESH_INTERNAL
  Ports:
    Name:      http
    Number:    80
    Protocol:  http
  Resolution:  DNS
Events:        <none>
```
East:
```
Name:         default.greeting-sample-showgtp.global-se
Namespace:    admiral-sync
Labels:       identity=greeting-sample-showgtp
Annotations:  <none>
API Version:  networking.istio.io/v1beta1
Kind:         ServiceEntry
Metadata:
  Creation Timestamp:  2021-01-25T23:41:37Z
  Generation:          8
  Resource Version:    63962592
  Self Link:           /apis/networking.istio.io/v1beta1/namespaces/admiral-sync/serviceentries/default.greeting-sample-showgtp.global-se
  UID:                 ea88024a-c6a1-471d-a14d-f90af02364f1
Spec:
  Addresses:
    240.0.10.6
  Endpoints:
    Address:   greeting.sample-showgtp.svc.cluster.local
    Locality:  us-east-1
    Ports:
      Http:    80
    Address:   <WEST-NLB>
    Locality:  us-west-2
    Ports:
      Http:  15443
  Hosts:
    default.greeting-sample-showgtp.global
  Location:  MESH_INTERNAL
  Ports:
    Name:      http
    Number:    80
    Protocol:  http
  Resolution:  DNS
Events:        <none>
```
West
```Name:         default.greeting-sample-showgtp.global-se
Namespace:    admiral-sync
Labels:       identity=greeting-sample-showgtp
Annotations:  <none>
API Version:  networking.istio.io/v1beta1
Kind:         ServiceEntry
Metadata:
  Creation Timestamp:  2021-01-23T02:13:08Z
  Generation:          1996
  Resource Version:    61182242
  Self Link:           /apis/networking.istio.io/v1beta1/namespaces/admiral-sync/serviceentries/default.greeting-sample-showgtp.global-se
  UID:                 220c5401-3b2e-422a-a1c8-0152a825c247
Spec:
  Addresses:
    240.0.10.6
  Endpoints:
    Address:   greeting.sample-showgtp.svc.cluster.local
    Locality:  us-west-2
    Ports:
      Http:  80
  Hosts:
    default.greeting-sample-showgtp.global
  Location:  MESH_INTERNAL
  Ports:
    Name:      http
    Number:    80
    Protocol:  http
  Resolution:  DNS
Events:        <none>
```
